### ISSUE TITLE
更新域名后没有自动签到

### ISSUE THREAD

**Issue by buzuosheng** [moreant/auto-checkin-sockboom#6]
前几天sockboom网站域名后缀改为.tv，我在github actions中也改了，但是在sockboom中没有发现自动签到，这是怎么回事呢

**Comment by moreant** [comment]
这个地方改漏了

https://github.com/buzuosheng/auto-checkin-sockboom/blob/ee1a4908eb8509f72be64de171706ca669e8341d/.github/workflows/main.yml#L31
